# Generated by Django 5.0.10 on 2025-01-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_query", models.CharField(max_length=20)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
