# Generated by Django 5.0.10 on 2025-01-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoCandleStick",
        ),
    ]
