# Generated by Django 5.0.10 on 2025-01-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_cryptosearch_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptosearch",
            old_name="price",
            new_name="current_price",
        ),
    ]
